import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
      <header className="bg-gray-800 text-white p-4 flex justify-between items-center">
      <div className="text-xl">Logo</div>
      <nav>
        <ul className="flex space-x-4">
          <li>
            <a href="/" className="hover:text-gray-300">Home</a>
          </li>
          <li>
            <a href="/buy" className="hover:text-gray-300">Buy</a>
          </li>
          <li>
            <a href="/subcription" className="hover:text-gray-300">Subscription</a>
          </li>
        </ul>
      </nav>
    </header>
        
        {children}</body>
        
    </html>
  );
}
